In [1]:
import ir_datasets
import pandas as pd

### ir_datasets官网
[ir_datasets官网](https://ir-datasets.com/index.html)

### clirmatrix官网
[clirmatrix官网](https://www.cs.jhu.edu/~shuosun/clirmatrix/)

### 使用 ir_datasets 来加载并下载 clirmatrix Bi139 数据

`ir_datasets.load('clirmatrix/{doc_lang}/{bi139-base|bi139-full}/{query_lang}/{train|dev|test1|test2}')`

eg：`ir_datasets.load('clirmatrix/kk/bi139-full/zh/train')`

In [2]:
dataset = ir_datasets.load('clirmatrix/kk/bi139-full/zh/train')

[INFO] If you have a local copy of http://www.cs.jhu.edu/~shuosun/clirmatrix/data/downloads.json.gz, you can symlink it here to avoid downloading it again: C:\Users\yanghe\.ir_datasets\downloads\371cc532aca236759bd3602eb6ce2181
[INFO] [starting] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/downloads.json.gz
[INFO] [finished] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/downloads.json.gz: [00:37] [5.14MB] [138kB/s]

In [3]:
dataset.docs_count()

[INFO] If you have a local copy of https://macavaney.us/clirmatrix-metadata.json.lz4, you can symlink it here to avoid downloading it again: C:\Users\yanghe\.ir_datasets\downloads\537510770a139b25dd12684c6711c91a
[INFO] [starting] https://macavaney.us/clirmatrix-metadata.json.lz4
[INFO] [finished] https://macavaney.us/clirmatrix-metadata.json.lz4: [00:05] [6.52MB] [1.29MB/s]

230047

In [4]:
for doc in dataset.docs_iter()[:10]:
  print(doc)

[INFO] [starting] building docstore
[INFO] If you have a local copy of http://www.cs.jhu.edu/~shuosun/clirmatrix/data/DOCS/kk.tsv.gz, you can symlink it here to avoid downloading it again: C:\Users\yanghe\.ir_datasets\downloads\a0162f3fce53e186b4e1eed30aacb42d
[INFO] [starting] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/DOCS/kk.tsv.gz

                                                                                                     [INFO] [finished] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/DOCS/kk.tsv.gz: [08:48] [60.3MB] [114kB/s]
docs_iter: 230047doc [09:03, 423.46doc/s]
[INFO] [finished] docs_iter: [09:03] [230047doc] [423.46doc/s]
[INFO] [finished] building docstore [09:03]

GenericDoc(doc_id='548262', text='Буын (фонетика) — сөйлеу мүшелерінің тұтастай қимылынан пайда болған бір немесе бірнеше дыбыстық тіркесі. Буынды тек дауысты дыбыстар ғана құрайды. Дауысты фонема өз алдына тұрып та, төңірегіне дауыссыздарды алып тұрып та Буын құрай алады. Буынға тән негізгі белгілер: 1) дауысты дыбыссыз Буын болмайды; 2) дауысты дыбыстың өзі де Буын бола алады (а-та, ә-же, а-па, т.б.). Бір Буында бірден артық дауысты болмайды, ал сөздің құрамында қанша дауысты дыбыс болса, сонша Буын болады (жұ-ды-рық, қа-лам, мек-теп); 4) Буында мағына болмайды; 5) Тілімізде байырғы сөздер, сондай-ақ, Буындар да екі дауыссыздан басталмайды (сқақ, рза, сланов деп жазбаймыз, дұрысы: сықақ, риза, сыланов түрінде келеді); 6) қазақ тілінде басқы (сөздің басындағы) Буын ғана дауыстыдан басталуы мүмкін, қалған жағдайда (екінші, үшінші, т.б.) Буындар дауыстыдан басталмайды. Тасымалдың дауыстыдан басталмайтыны содан (кә-сіп, қыз-ғал-дақ, мә-сі); 7) сөздердің айтылуындағы Буын саны мен жазылудағы Буын саны әрқашан бір-біріне сай келуі шарт емес (айтылуда: Сар-ар-қа, кел-ал-май-ды, ал жазылуда: Са-ры-ар-қа, ке-ле ал-май-ды).')
GenericDoc(doc_id='108899', text='Таужыныстармен бірге жаралған шашыранды органикалық заттардың генетикалық түрі және катагендік өзгерістерге ұшырау ережесі тұрғысынан дараланатын топтамалары. Шашыранды органикалық заттардың генетикалық түрі сол шашыранды заттардан таужыныстарға қышқылдармен (HC1 және HF) әсер ету нәтижесінде бөлініп алынған және одан таушайыр тектестері мен гумин қышқылдарын аластағаннан кейінгі калған көмірпетрографиялық және химиялық сипаттарымен анықталады. Мұнай және газ геологиясы танымдық және кәсіптік-технологиялық терминдерінің түсіндірме сөздігі. Анықтамалық басылым. — Алматы: 2003 жыл. ISBN 9965-472-27-0')
GenericDoc(doc_id='548634', text='Қарбасқан - Қарағанды облысы Қарқаралы ауданының солтүстігіндегі тау. Қарасор көлінен оңтүстікке қарай 15-20 км, Қарқаралы қаласынан солтүстікке қарай 30 км жерде орналасқан. Оңтүстіктен солтүстік-шығысқа қарай 1,5-2 км-ге созылып жатыр, енді жері 1 км. Абсолюттік биіктігі 745 м. Беткейлері көбіне жайпақ, аз тілімденген, батысы тік жарлы. Пермь гранитоидтарынан түзілген. Толық қалыптасып жетілмеген қызғылт қоңыр, саздақты топырақ кездеседі. Шығысы батпақты, оңтүстік және солтүстік етектері сортаңды болып келеді. Қазақстан табиғаты:Энциклопедия / Бас ред. Б.Ө.Жақып. - Алматы:" Қазақ энциклопедиясы" ЖШС, 2011. Т.З. - 304 бет. ISBN 9965-893-64-0 (Т.З.), ISBN 9965-893-19-5')
GenericDoc(doc_id='65354', text='Мәліметтерді жеткізудің программаланатын мультиплексоры (программируемый мультиплексор передачи данных) — бақылаумен бірге мәліметтерді программаланған өңдеу, адрестеуді түрлендіру мен хабарламаны танып-білу, қарастырылған мәліметтерді жеткізу мультиплексоры. Қазақ тілі терминдерінің салалық ғылыми түсіндірме сөздігі: Информатика және компьютерлік техника / Жалпы редакциясын басқарған – түсіндірме сөздіктер топтамасын шығару жөніндегі ғылыми-баспа бағдарламасының ғылыми жетекшісі, педагогика ғылымдарының докторы, профессор, Қазақстан Республикасы Мемлекеттік сыйлығының лауреаты А. Қ. Құсайынов. – Алматы: «Мектеп» баспасы» ЖАҚ, 2002 жыл. – 456 бет. ISBN 5-7667-8284-5')
GenericDoc(doc_id='561390', text='Уллахпара (баңлаша উল্লাপাড়া, ағылш. Ullahpara)\xa0—Баңладештің солтүстігінде орналасқан қала және муниципалитет. Муниципалитет \xa01984 жылы\xa0қаланған.Қала алаңы 12,70\xa0км²-ге тең. 2001 жылғы санақ бойынша, қалада 36\xa0766 адам тұрып жатқан, оның ішінде 52,31\xa0% еркектер, 47,69\xa0% әйелдер. Қала тығыздығы 1\xa0км²-ге 2895 адам. Сауаттылық деңгейі 46,33\xa0% (Баңладештің орташа көрсеткіші 43,1\xa0%). Уллахпара в\xa0(ағыл.)(англ.)')
GenericDoc(doc_id='74517', text='Уақыт бойынша бөлінетін екіжақты тарату (орыс. Передача с временными разделением; TDD ағылш. Time Division Duplex) — бір кадрды әр түрлі уақыт аралығында қабылдау мен таратуды арнаны тығыздау арқылы бір тасымалдаушы бойынша сандық ақпаратты екіжақты тарату. Уақыт бойынша бөлінетін екіжақты тарату қызметі белгілі аймақта төмен жылдамдықта таралатын пика және микроұяларға арналған. Қазақ тілі терминдерінің салалық ғылыми түсіндірме сөздігі: Электроника, радиотехника және байланыс. — Алматы: «Мектеп» баспасы, 2007 жыл. ISBN 9965-36-448-6')
GenericDoc(doc_id='561414', text='Сан-Хавьер (ис. San Javier)\xa0— Испаниядағы муниципалитет,\xa0Мурсия\xa0автономды бірлестігінің құрамындағы Мурсия шет аймағына кіреді. Муниципалитет Мар-Менор\xa0аймағында (комарка) орналасқан. Ауданы 74,2 км² құрайды. Халық саны 31820 адам (2010 жыл). Қаланың маңында Мурсия автономды бірлестігінің\xa0әуе қатынасын қамтитын\xa0Мурсия-Сан-Хавьер\xa0әуежайы орналасқан. Әкімшілік жағынан муниципалитетке Ла-Манга\xa0мүйісінің бөлігі, Мар-Менор\xa0аралдары: Исла-Майор, Пердигера, Сьерво, Сухето, Ронделья, сонымен қатар Жерорта теңізіндегі\xa0Исла-Гроса\xa0аралы қарасты. Mancomunidad del Mar Menor Página del Ayuntamiento de San Javier Biblioteca Pública Municipal de San Javier')
GenericDoc(doc_id='110244', text='Жылтырсыр бояу қаптаны радиациялық химиялык, тәсілмен қатайтатын (кептіретін) құрылғылар (орыс. установки для отверждения (сушки) лакокрасочных покрытий радиационно-химическим методом) — жиһаз жасау өндірісінде бұйымдардын беттерінің арнайы жылтырсыр бояу қапталарын қатайтуға (кептіруге) арналған құрылғылар. Өңделетін бөлшектің өлшемдері: ұзындығы 1500 мм-ге дейін, ені 1000 мм-ге дейін, биіктігі 50 мм-ге дейін. Полиграфия, өлшеу техникасы, ағаш өңдеу жабдыктары және металл өңдеу техникасы мен технологиясы: Қазақша-орысша терминдердің түсіндірме сөздігі.')
GenericDoc(doc_id='561504', text='Аршат Мұратұлы Оразов (14 ақпан 1981, Ақтөбе облысы, Ойыл ауданы, Сарбие ауылы) - қазақстандық блогер, Kerekinfo.kz блог-платформасының құрушысы. Блогер, медиалектор, ІТ маман ретінде танымал. Қазақ интернетінде ҚазнетДода, Блогиада жобаларының авторы. Бірқатар қазақ сайттарының құрушысы. Блогер ретінде жазатын тақырыптары: ақпараттық қауіпсіздік, спорт, веб, ІТ, қоғам. 1997 жылы Ақтөбе Қазақ-Түрік лицейін бітірді. 2004 жылы Түркияның Анадолу Университеті Туризм факультетін аяқтап, жоғары білім алып шықты. 2006 - 2010 жылдары Ақтөбе облыстық әкімдігінде Ақпараттық технологиялар және жүйелер бөлімінде бас инженер қызметін атқарды. Электронды үкімет бағдарламасын енгізуде еңбек сіңірді. Ақтөбе облыстық әкімдігінің веб-сайтын құрды. 2010 - 2013 жылдары "Егемен Қазақстан" газетінің веб-сайтын басқарды. Сайтты жаңадан жасақтап шықты. 2013 - 2014 жылдары "Нұрмедиа" холдингінің Munara.kz жаңалықтар сайтын басқарды. 2015 жылдан бастап "Жігер.Абырой.')
GenericDoc(doc_id='63395', text='Созылмалы туберкулездің интоксикациясы — реактивтілік өзгерісі фонындағы туберкулездің ерте сатысында дамитын күй; Пульмонология терминдерінің орысша-қазақша түсіндірме сөздігі Пульмонология терминдерінің орысша-қазақша түсіндірме сөздігі. Алматы: Ана тілі. 1996. ISBN 5-630-00473-5')

In [5]:
pd.DataFrame(dataset.queries_iter())

[INFO] If you have a local copy of http://www.cs.jhu.edu/~shuosun/clirmatrix/data/BI-139/full/zh/zh.kk.train.jl.gz, you can symlink it here to avoid downloading it again: C:\Users\yanghe\.ir_datasets\downloads\75375b7f156a75e6b3222da6dd8cd604
[INFO] [starting] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/BI-139/full/zh/zh.kk.train.jl.gz
[INFO] [finished] http://www.cs.jhu.edu/~shuosun/clirmatrix/data/BI-139/full/zh/zh.kk.train.jl.gz: [02:53] [29.8MB] [171kB/s]

       query_id text
0            13   数学
1            18   哲学
2            21   文學
3            22   历史
4            39   民族
...         ...  ...
574782  6865913  张志明
574783  6867022   张策
574784  6867032   罗斌
574785  6868109   彭程
574786  6868236  万建中

[574787 rows x 2 columns]

In [6]:
pd.DataFrame(dataset.qrels_iter())

        query_id  doc_id  relevance iteration
0             13    9511          6         0
1             13  199261          5         0
2             13   27444          4         0
3             13   52730          4         0
4             13   28319          4         0
...          ...     ...        ...       ...
5816536  6868109  302935          1         0
5816537  6868109  209195          1         0
5816538  6868109  238563          1         0
5816539  6868109  204835          1         0
5816540  6868236   25182          4         0

[5816541 rows x 4 columns]